### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to 1.9.0

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by alexAubin — APPROVED** [review]

**Comment by ericgaspar** [comment]
This is the RC; waiting for the final release...

**Comment by tituspijean** [comment]
Official release released : https://github.com/hedgedoc/hedgedoc/releases/tag/1.9.0

:)

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
